"""Schema umbrella — import from here; internal layout is an implementation detail."""

from app.schemas.content import (
    MaterialCreate,
    MaterialListItem,
    MaterialListResponse,
    MaterialResponse,
)
from app.schemas.identity import (
    LoginRequest,
    OrganizationCreate,
    OrganizationMembershipCreate,
    OrganizationMembershipRead,
    OrganizationRead,
    PermissionRead,
    RefreshRequest,
    RoleRead,
    TokenResponse,
    UserCreate,
    UserRead,
    UserUpdate,
)
from app.schemas.learning import (
    InteractionCreate,
    InteractionResponse,
    ScenarioGenerateRequest,
    ScenarioInteractionsResponse,
    ScenarioListItem,
    ScenarioListResponse,
    ScenarioResponse,
)
from app.schemas.governance import (
    ApprovalBatchCreate,
    ApprovalBatchRead,
    ClinicalReviewCreate,
    ClinicalReviewRead,
    ContentFailureSummary,
    ContentItemCreate,
    ContentItemListItem,
    ContentItemListResponse,
    ContentItemRead,
    ContentVersionCreate,
    ContentVersionRead,
    EvidenceSourceCreate,
    EvidenceSourceRead,
    EvidenceSourceUpdate,
    FailureAnalyticsCreate,
    FailureHotspot,
    OrgWeaknessMap,
    PublicationRecordRead,
    PublishRequest,
    UnpublishRequest,
)
from app.schemas.platform import HealthResponse, PaginatedResponse

__all__ = [
    # Platform
    "HealthResponse",
    "PaginatedResponse",
    # Content
    "MaterialCreate",
    "MaterialResponse",
    "MaterialListItem",
    "MaterialListResponse",
    # Learning
    "ScenarioGenerateRequest",
    "ScenarioResponse",
    "ScenarioListItem",
    "ScenarioListResponse",
    "InteractionCreate",
    "InteractionResponse",
    "ScenarioInteractionsResponse",
    # Identity / Auth
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "LoginRequest",
    "TokenResponse",
    "RefreshRequest",
    "OrganizationCreate",
    "OrganizationRead",
    "OrganizationMembershipCreate",
    "OrganizationMembershipRead",
    "RoleRead",
    "PermissionRead",
    # Governance
    "ContentItemCreate",
    "ContentItemRead",
    "ContentItemListItem",
    "ContentItemListResponse",
    "ContentVersionCreate",
    "ContentVersionRead",
    "EvidenceSourceCreate",
    "EvidenceSourceUpdate",
    "EvidenceSourceRead",
    "ApprovalBatchCreate",
    "ApprovalBatchRead",
    "ClinicalReviewCreate",
    "ClinicalReviewRead",
    "PublishRequest",
    "UnpublishRequest",
    "PublicationRecordRead",
    "FailureAnalyticsCreate",
    "FailureHotspot",
    "ContentFailureSummary",
    "OrgWeaknessMap",
]
